/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glavni;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.Connection;
import java.util.Enumeration;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import konekcija.konekcija;
import maticni.MaticniPodaciJPanel;
import maticni.PttBrojeviJPanel;
import terminal_pos.TerminalJPanel;

/**
 *
 * @author Pionir SU
 */
public class Glavni extends javax.swing.JFrame {

    /**
     * Creates new form Glavni
     */
    Glavni parent = this;
    public Connection conn;

    public Glavni() {

        initComponents();
        konekcija n = new konekcija();
        conn = n.konekcija();
        setLocationRelativeTo(null);
        ucitajMenu();
        jSplitPane1.setDividerLocation(.2f);
//                DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer) jTree1.getCellRenderer();
//                
//                Icon closedIcon = new ImageIcon("pictures/fileopen.png");
//                Icon openIcon = new ImageIcon("pictures/filefind.png");
//                Icon leafIcon = new ImageIcon("pictures/fileopen.png");
//                
//                renderer.setClosedIcon(closedIcon);
//                renderer.setOpenIcon(openIcon);
//                renderer.setLeafIcon(leafIcon);
//                
//                this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jXTaskPaneBeanInfo1 = new org.jdesktop.swingx.JXTaskPaneBeanInfo();
        } catch (java.beans.IntrospectionException e1) {
            e1.printStackTrace();
        }
        try {
            jXTaskPaneBeanInfo2 = new org.jdesktop.swingx.JXTaskPaneBeanInfo();
        } catch (java.beans.IntrospectionException e1) {
            e1.printStackTrace();
        }
        jScrollPane2 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(8);
        jSplitPane1.setAutoscrolls(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Naslovna1636x1089-44a.jpg"))); // NOI18N
        jLabel2.setToolTipText("Best POS solution in Serbia");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setIconTextGap(0);
        jLabel2.setMaximumSize(new java.awt.Dimension(1600, 513));
        jLabel2.setMinimumSize(new java.awt.Dimension(1600, 513));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1570, 413));
        jTabbedPane2.addTab("tab1", jLabel2);

        jSplitPane1.setRightComponent(jTabbedPane2);

        jXTaskPane1.setTitle("Menu");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jXTaskPane1.getContentPane().add(jPanel3);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ComputerSmall.png"))); // NOI18N
        jXTaskPane2.setTitle("Best POS - SMARTPOS ");
        jXTaskPane2.setToolTipText("Main menu");
        jXTaskPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jXTaskPaneContainer1.add(jXTaskPane2);
        jXTaskPaneContainer1.add(jXTaskPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane3.addTab("tab2", jScrollPane1);

        jSplitPane1.setLeftComponent(jTabbedPane3);

        jScrollPane2.setViewportView(jSplitPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Glavni().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPaneBeanInfo jXTaskPaneBeanInfo1;
    private org.jdesktop.swingx.JXTaskPaneBeanInfo jXTaskPaneBeanInfo2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    // End of variables declaration//GEN-END:variables

    private void ucitajMenu() {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultMutableTreeNode style = new DefaultMutableTreeNode("Smart POS");
        DefaultMutableTreeNode color = new DefaultMutableTreeNode("Matični podaci");
        DefaultMutableTreeNode font = new DefaultMutableTreeNode("Prodaja");
        style.add(color);
        style.add(font);
        DefaultMutableTreeNode red = new DefaultMutableTreeNode("Države");
        DefaultMutableTreeNode blue = new DefaultMutableTreeNode("Ptt brojevi");
        DefaultMutableTreeNode black = new DefaultMutableTreeNode("Terminal");
        DefaultMutableTreeNode green = new DefaultMutableTreeNode("green");
        color.add(red);
        color.add(blue);
        font.add(black);
        color.add(green);
        final JTree jt = new JTree(style);
//        final Font currentFont = tree.getFont();
//        Font bigFont = new Font(currentFont.getName(), currentFont.getStyle(), currentFont.getSize() + 10);
//        jt.setFont(bigFont);
//        jt.setFont(font);
          Font font1 = jt.getFont();
          int size = font1.getSize();
//          jt.setFont(font1, size);
//  jt.setFont(font1.getSize() + 2); // . .deriveFont(10.0f));

final Font currentFont = jt.getFont();
//final Font bigFont = new Font("Tahoma", Font.PLAIN, 15);
final Font bigFont = new Font("Arial", Font.PLAIN, 15);
// final Font bigFont = new Font(currentFont.getName(), currentFont.getStyle(), currentFont.getSize() + 2);
jt.setFont(bigFont);

        expandTree(jt, true);
//    jt.expandPath(style);
        jXTaskPane2.add(jt);
//    f.setSize(200,200);
//    f.setVisible(true);
//        JTextField jtf = new JTextField("", 20);
//        add(jtf, BorderLayout.SOUTH)

//        JButton button = new JButton();
//        try {
//
//            button.setIcon(new ImageIcon(ImageIO.read(Thread.currentThread().getContextClassLoader().getResourceAsStream("/pictures/Naslovna.jpeg"))));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
        JButton button = new JButton();
        try {
            Image img = ImageIO.read(getClass().getResource("pictures/Naslovna.png"));
            button.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        jTabbedPane2.add(button);

//        JLabel jl = new JLabel(new ImageIcon("pictures/Naslovna.jpeg"));
//        jTabbedPane2.add(jl);
        jt.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                doMouseClicked(me);
            }

            void doMouseClicked(MouseEvent me) {

                TreePath tp = jt.getPathForLocation(me.getX(), me.getY());
                if (tp != null) {
                    jLabel1.setText(tp.toString());
                } else {
                    jLabel1.setText("");
                }

                System.out.print(tp.toString());

                if (tp.toString().equals("[Smart POS, Matični podaci, Države]")) {

                    /*
                    MaticniPodaciJPanel mpjp = new MaticniPodaciJPanel(parent, conn, "drzave");
                    mpjp.setOpaque(false);
                    jTabbedPane2.add(mpjp);

                    int aa = jTabbedPane2.indexOfComponent(mpjp);
                    jTabbedPane2.setTabComponentAt(jTabbedPane2.indexOfComponent(mpjp), getTitlePanel(jTabbedPane2, mpjp, "Države"));
                    int selectedIndex = jTabbedPane2.getSelectedIndex();

                    System.out.println("Default Index:" + selectedIndex);
                    jTabbedPane2.setSelectedIndex(jTabbedPane2.getTabCount() - 1);

                    selectedIndex = jTabbedPane2.getSelectedIndex();

                    System.out.println("New Index:" + selectedIndex);
                    */
                    
                    
/*                  jTabbedPane2.grabFocus();
                    jTabbedPane2.requestFocus();
                    get the currently selected index for this tabbedpane
*/

                } else if (tp.toString().equals("[Smart POS, Matični podaci, Ptt brojevi]")) {

                    /*
                    PttBrojeviJPanel mpjp = new PttBrojeviJPanel(parent, conn, "ptt_brojevi");
                    mpjp.setOpaque(false);
                    jTabbedPane2.add(mpjp);
                    int aa = jTabbedPane2.indexOfComponent(mpjp);
                    jTabbedPane2.setTabComponentAt(jTabbedPane2.indexOfComponent(mpjp), getTitlePanel(jTabbedPane2, mpjp, "Ptt brojevi"));
                    int selectedIndex = jTabbedPane2.getSelectedIndex();
                    jTabbedPane2.setSelectedIndex(jTabbedPane2.getTabCount() - 1);
                    selectedIndex = jTabbedPane2.getSelectedIndex();
                    */
                }
                
                else if (tp.toString().equals("[Smart POS, Prodaja, Terminal]")) {

                    TerminalJPanel mpjp = new TerminalJPanel(parent, conn);
                    mpjp.setOpaque(false);
                    jTabbedPane2.add(mpjp);
                    int aa = jTabbedPane2.indexOfComponent(mpjp);
                    jTabbedPane2.setTabComponentAt(jTabbedPane2.indexOfComponent(mpjp), getTitlePanel(jTabbedPane2, mpjp, "Terminal"));
                    int selectedIndex = jTabbedPane2.getSelectedIndex();
                    jTabbedPane2.setSelectedIndex(jTabbedPane2.getTabCount() - 1);
                    selectedIndex = jTabbedPane2.getSelectedIndex();

                }                

            }

//        private Component getTitlePanel(JTabbedPane jTabbedPane2, JPanel panel, String tab1) {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//        }
            private JPanel getTitlePanel(final JTabbedPane tabbedPane, final JPanel panel, String title) {
                JPanel titlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
                titlePanel.setOpaque(false);
                JLabel titleLbl = new JLabel(title);
                titleLbl.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 5));
                titlePanel.add(titleLbl);
                JButton closeButton = new JButton("x");
                closeButton.setForeground(Color.red); // .setBackground(Color.RED);
                closeButton.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        tabbedPane.remove(panel);
                    }
                });
                titlePanel.add(closeButton);
                return titlePanel;
            }

        });
    }

    private void expandTree(JTree tree, boolean expand) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        TreeNode root = (TreeNode) tree.getModel().getRoot();
        expandAll(tree, new TreePath(root), expand);
    }

    private void expandAll(JTree tree, TreePath path, boolean expand) {
        TreeNode node = (TreeNode) path.getLastPathComponent();

        if (node.getChildCount() >= 0) {
            Enumeration enumeration = node.children();
            while (enumeration.hasMoreElements()) {
                TreeNode n = (TreeNode) enumeration.nextElement();
                TreePath p = path.pathByAddingChild(n);

                expandAll(tree, p, expand);
            }
        }

        if (expand) {
            tree.expandPath(path);
        } else {
            tree.collapsePath(path);
        }
    }

}
